spring.application.name=personal-app

spring.cloud.gcp.project-id=personal-app-488917
# TODO: Remove for production.
spring.cloud.gcp.credentials.impersonate-service-account=personal-app-service@personal-app-488917.iam.gserviceaccount.com
app.pubsub.email.topic=email-events-topic