spring.application.name=personal-app
spring.main.lazy-initialization=true
#
spring.cloud.gcp.project-id=personal-app-488917
#
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false
#
server.port=${PORT:8080}
#
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.me.silon=INFO
#
recaptcha.sitekey=6LeJy5ksAAAAAFITjXdqqyAON8p0MNBpj65wvK8i