spring.application.name=email-service

spring.cloud.gcp.project-id=personal-app-488917
# TODO: Remove for production.
spring.cloud.gcp.credentials.impersonate-service-account=email-service@personal-app-488917.iam.gserviceaccount.com
app.pubsub.email.subscription=email-events-subscription